### ISSUE TITLE
Port to python3

### ISSUE THREAD

**Issue by shubhamchaudhary** [shubhamchaudhary/universal#5]
Looking for contributions to port this to python3.  
Python3 is more common and has a wider range of people who understand it. We can start by implementing some basic functionality and then go in deeper.

**Comment by harsimrans** [comment]
So this issue is still open, i'm willing to work on this. Can you suggest how to go about starting this port to python3 ?

**Comment by shubhamchaudhary** [comment]
Awesome. Checkout python port branch I just pushed https://github.com/shubhamchaudhary/universal/tree/python-port

**Comment by harsimrans** [comment]
Just checked out the python port branch.
compiles C, C++, Java, Python just sometimes minor glithches.

Will start adding functions by taking reference from universal.sh

**Comment by harsimrans** [comment]
Couldn't figure out properly how to update the branch/create pull request for the branch.
I have created my own branch python-port-harsimran.
i have implemented some functions which you can check out at: https://github.com/harsimrans/universal/blob/python-port-harsimran/python/universal.py

Am i doing the branching thing right (i have a strong feeling that it's not)?
